ARG NODE_VERSION
FROM node:${NODE_VERSION}-alpine

WORKDIR /app

COPY *.json ./
COPY ./src ./src
COPY entrypoint-migrations.sh ./

RUN npm i -g ts-node tsconfig-paths
RUN npm ci --quiet && npm run build

EXPOSE 3000

CMD ["/bin/sh", "entrypoint-migrations.sh"]
